import { Routes } from '@angular/router';
import { AsyncSignalDemoComponent } from './demos/async-signal-demo.component';
import { DebounceSignalDemoComponent } from './demos/debounce-signal-demo.component';
import { ExtendSignalDemoComponent } from './demos/extend-signal-demo.component';
import { FilterSignalDemoComponent } from './demos/filter-signal-demo.component';
import { LiftSignalDemoComponent } from './demos/lift-signal-demo.component';
import { MapSignalDemoComponent } from './demos/map-signal-demo.component';
import { ReduceSignalDemoComponent } from './demos/reduce-signal-demo.component';
import { SequenceSignalDemoComponent } from './demos/sequence-signal-demo.component';
import { SignalToIteratorDemoComponent } from './demos/signal-to-iterator-demo.component';
import { TimerSignalDemoComponent } from './demos/timer-signal-demo.component';
import { TweenSignalDemoComponent } from './demos/tween-signal-demo.component';
import { HomeComponent } from './home.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'async-signal', component: AsyncSignalDemoComponent },
  { path: 'debounce-signal', component: DebounceSignalDemoComponent },
  { path: 'extend-signal', component: ExtendSignalDemoComponent },
  { path: 'filter-signal', component: FilterSignalDemoComponent },
  { path: 'lift-signal', component: LiftSignalDemoComponent },
  { path: 'map-signal', component: MapSignalDemoComponent },
  { path: 'reduce-signal', component: ReduceSignalDemoComponent },
  { path: 'signal-to-iterator', component: SignalToIteratorDemoComponent },
  { path: 'sequence-signal', component: SequenceSignalDemoComponent },
  { path: 'timer-signal', component: TimerSignalDemoComponent },
  { path: 'tween-signal', component: TweenSignalDemoComponent },
  { path: '**', redirectTo: '' }
];
