export default {
  "tsconfig.json": "/* To learn more about this file see: https://angular.io/config/tsconfig. */\n{\n  \"compileOnSave\": false,\n  \"compilerOptions\": {\n    \"outDir\": \"./dist/out-tsc\",\n    \"forceConsistentCasingInFileNames\": true,\n    \"strict\": true,\n    \"noImplicitOverride\": true,\n    \"noPropertyAccessFromIndexSignature\": true,\n    \"noImplicitReturns\": true,\n    \"noFallthroughCasesInSwitch\": true,\n    \"esModuleInterop\": true,\n    \"sourceMap\": true,\n    \"declaration\": false,\n    \"downlevelIteration\": true,\n    \"experimentalDecorators\": true,\n    \"moduleResolution\": \"node\",\n    \"importHelpers\": true,\n    \"target\": \"ES2022\",\n    \"module\": \"ES2022\",\n    \"useDefineForClassFields\": false,\n    \"lib\": [\"ES2022\", \"dom\"]\n  },\n  \"angularCompilerOptions\": {\n    \"enableI18nLegacyMessageIdFormat\": false,\n    \"strictInjectionParameters\": true,\n    \"strictInputAccessModifiers\": true,\n    \"strictTemplates\": true\n  }\n}\n",
  "tsconfig.app.json": "/* To learn more about this file see: https://angular.io/config/tsconfig. */\n{\n  \"extends\": \"./tsconfig.json\",\n  \"compilerOptions\": {\n    \"outDir\": \"./out-tsc/app\",\n    \"types\": []\n  },\n  \"files\": [\"src/main.ts\"],\n  \"include\": [\"src/**/*.d.ts\"]\n}\n",
  "tailwind.config.js": "/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  content: [\n    './src/**/*.{html,ts}',\n  ],\n  plugins: [\n    require('daisyui')\n  ],\n  daisyui: {\n    themes: [\"light\", \"dark\"],\n  }\n}\n\n",
  "package.json": "{\n  \"name\": \"angular-signal-generators-demo\",\n  \"private\": true,\n  \"scripts\": {\n    \"ng\": \"ng\",\n    \"start\": \"ng serve\",\n    \"build\": \"ng build\"\n  },\n  \"dependencies\": {\n    \"@angular/common\": \"^21.0.0\",\n    \"@angular/compiler\": \"^21.0.0\",\n    \"@angular/core\": \"^21.0.0\",\n    \"@angular/forms\": \"^21.0.0\",\n    \"@angular/platform-browser\": \"^21.0.0\",\n    \"@ddtmm/angular-signal-generators\": \"^4.0.0\",\n    \"rxjs\": \"^7.8.2\",\n    \"tslib\": \"^2.6.2\"\n  },\n  \"devDependencies\": {\n    \"@angular/build\": \"^21.0.0\",\n    \"@angular/cli\": \"^21.0.0\",\n    \"@angular/compiler-cli\": \"^21.0.0\",\n    \"@tailwindcss/postcss\": \"^4.0.0\",\n    \"autoprefixer\": \"^10.4.19\",\n    \"daisyui\": \"^5.0.0\",\n    \"postcss\": \"^8.5.4\",\n    \"tailwindcss\": \"^4.0.0\",\n    \"typescript\": \"~5.9.3\"\n  },\n  \"overrides\": {\n    \"@angular-devkit/build-angular\": {\n      \"piscina\": \"~4.2.0\"\n    }\n  }\n}\n",
  "angular.json": "{\n  \"$schema\": \"./node_modules/@angular/cli/lib/config/schema.json\",\n  \"newProjectRoot\": \"projects\",\n  \"projects\": {\n    \"demo\": {\n      \"architect\": {\n        \"build\": {\n          \"builder\": \"@angular/build:application\",\n          \"configurations\": {\n            \"development\": {\n              \"optimization\": false,\n              \"extractLicenses\": false,\n              \"sourceMap\": true\n            },\n            \"production\": {\n              \"outputHashing\": \"all\"\n            }\n            \n          },\n          \"options\": {\n            \"assets\": [],\n            \"index\": \"src/index.html\",\n            \"browser\": \"src/main.ts\",\n            \"outputPath\": \"dist/demo\",\n            \"scripts\": [],\n            \"styles\": [\"src/styles.css\"],\n            \"tsConfig\": \"tsconfig.app.json\"\n          }\n        },\n        \"serve\": {\n          \"builder\": \"@angular/build:dev-server\",\n          \"configurations\": {\n            \"development\": {\n              \"buildTarget\": \"demo:build:development\"\n            },\n            \"production\": {\n              \"buildTarget\": \"demo:build:production\"\n            }\n          },\n          \"defaultConfiguration\": \"development\"\n        }\n      },\n      \"prefix\": \"app\",\n      \"projectType\": \"application\",\n      \"root\": \"\",\n      \"schematics\": {},\n      \"sourceRoot\": \"src\"\n    }\n  },\n  \"version\": 1\n}\n",
  ".postcssrc.json": "{\n  \"plugins\": {\n    \"@tailwindcss/postcss\": {}\n  }\n}",
  "src/styles.css": "@import \"tailwindcss\";\n@plugin \"daisyui\";",
  "src/main.ts": "import { ChangeDetectionStrategy, Component, provideZonelessChangeDetection } from '@angular/core';\nimport { $$DemoClass$$ } from './$$DemoPath$$';\nimport { bootstrapApplication } from '@angular/platform-browser';\n\n@Component({\n  selector: 'app-root',\n  standalone: true,\n  imports: [$$DemoClass$$],\n  template: '<$$DemoSelector$$ />',\n  changeDetection: ChangeDetectionStrategy.OnPush\n})\nexport class AppComponent { }\n\nbootstrapApplication(AppComponent, { providers: [provideZonelessChangeDetection()] });\n",
  "src/index.html": "<!DOCTYPE html>\n<html lang=\"en\" data-theme=\"light\">\n  <head>\n    <title>My app</title>\n    <meta charset=\"UTF-8\" />\n  </head>\n  <body class=\"p-6 min-h-screen items-center flex flex-col gap-3\">\n    <app-root class=\"contents\">\n      <span class=\"text-xl\">Angular Signal Generators</span>\n      <img src=\"https://ddtmm.github.io/angular-signal-generators/assets/angular-signal-generators-logo.png\" alt=\"project logo\" class=\"w-20 inline\" />\n      <div>\n        Demo Loading\n        <span class=\"loading loading-spinner loading-sm align-text-bottom text-info\"></span>\n      </div>\n    </app-root>\n  </body>\n</html>\n"
}